### ISSUE TITLE
Unable to run game after 4.1.0 patch

### ISSUE THREAD

**Issue by BodenMcHale** [Oliveshark/breakhack#92]
I'm unable to play the game after installing update 4.1.0.

The game starts up to the main menu, graphical glitches, then shuts down. 
This whole process lasts about 2-3 seconds from hitting play to the game shutting down.

Here is a screenshot of the graphical glitch:
![Main Menu Glitch](https://github.com/user-attachments/assets/da30d354-0ace-45fb-941b-106d78e931af)

Possible cause could be the update to SDL3:
![SDL3 Update](https://github.com/user-attachments/assets/1e86d91f-5972-4890-8d8b-d3744be8d8a1)

**Specs:**
 - Game Version: 4.1.0
 - Platform: Steam / Desktop
 - OS: Windows 11
 - Architecture: 64 bit
 - GPU: NVIDIA GeForce RTX 3050 OEM 8gb
 - CPU: 12th Gen Intel(R) Core(TM) i5-12400F

**Attempted Fixes:**
 - Updated drivers
 - Reinstalled game
 - Verified integrity of game
 - Restarted computer

**Comment by LiquidityC** [comment]
Oh no. Right now all I can do is revert the build for Windows then I'll hav to try and figure out what the issue is. 

I don't have a windows computer though so it will be a bit of a process.

Thanks for posting the issue. I'll drop a message once I've done the revert.

**Comment by LiquidityC** [comment]
@BodenMcHale I reverted the default branch to the 4.0.3 release. 4.1.0 remains as the beta track. If you're up for helping me get some crash dumps from your computer then please ping me.

Right now I'm limited to linux. I'm also quite certain that it's not a general windows issue. I think it's a combination of the renderer pick for your setup that is causing havoc right now.

**Comment by LiquidityC** [comment]
Possibly related to: https://github.com/libsdl-org/SDL/issues/11820
Need to determine if it's vulkan that's being used for rendering which would either support or deny this. I'll introduce some renderer info in the debug logs during startup to make this easier.

**Comment by BodenMcHale** [comment]
> [@BodenMcHale](https://github.com/BodenMcHale) I reverted the default branch to the 4.0.3 release. 4.1.0 remains as the beta track. If you're up for helping me get some crash dumps from your computer then please ping me.

I'm down to share some logs to help fix this, what would you need me to do?

**Comment by LiquidityC** [comment]
@BodenMcHale Thanks. I appreciate any assistance I can get on this one. It'll be a while before I setup a windows machine in my office again.

Attached is a debug build for windows. Windows/Defender will almost certainly complain about it. You'll have to trust me. If you don't that's completely fine. Then the only option is to compile on your own.

If you start the game from cmd (might need to add some form of SmartSreen or Defender exception) it should spit out a lot of logs. I'd like to see those logs. In particular the ones relating to information about the **renderer**.

[breakhack-4.1.1-win32.zip](https://github.com/user-attachments/files/19017577/breakhack-4.1.1-win32.zip)

**Comment by BodenMcHale** [comment]
This is a bit funny, seems like `io_util.c` on line 10 isn't able to find the `click.wav` file.

I'd assume this is the SFX which plays on the menus when you hover over buttons.

![Image](https://github.com/user-attachments/assets/29f5c497-4ddf-47b9-9030-f0c022ce18df)

![Image](https://github.com/user-attachments/assets/33c53b5c-4cf9-4227-aa61-10f3a42685e9)

**Comment by LiquidityC** [comment]
Ah. I probably packaged it wrong. Never used the packing system to make a debug build before. 

I'm debug mode the executable needs to run with the assets and data folder in the same directory where you execute the binary. You can just get those from the repo. 

At least I compiled the binary correctly.

**Comment by BodenMcHale** [comment]
I moved the `breakhack.exe` you sent me to the main directory from the repo and got it running.

But I'm not quite sure what logs you're referring to, unless you mean the console log as I play?

If you print logs to a file, I'd appreciate if you could guide me towards a directory, I've looked around and been unable to find any.

But here is a 20 minute play session on [YouTube](https://www.youtube.com/watch?v=zCcPGmdH9nQ):
[![BreakHack Log 1 Debug](https://img.youtube.com/vi/zCcPGmdH9nQ/0.jpg)](https://www.youtube.com/watch?v=zCcPGmdH9nQ)

**Comment by LiquidityC** [comment]
And this is the exe that I compiled? Odd that it isn't crashing.

Regarding the logs I just need the ones that print to the console. Mostly the first ones that print when the game starts. If you could just copy and attach them here in the ticket. 

Thanks for all your assistance on this. Much appreciated.

**Comment by LiquidityC** [comment]
I see in the video that your experiencing some form of rendering buffer issue with the glitching. I think this is due to SDL 3 as well.

I can reproduce that on my setup too so I'll see if I can figure that out.

**Comment by BodenMcHale** [comment]
Got it, thank you for guidance

SDL logs
``` 
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:120][             initSDL()] Initializing SDL
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:129][             initSDL()] Initializing SDL_ttf
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:136][             initSDL()] Initializing gamepads
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:563][        initGamepads()] Found 0 joysticks
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:139][             initSDL()] Initializing SDL_mixer
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: direct3d11
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: direct3d12
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: direct3d
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: opengl
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: opengles2
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: vulkan
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: gpu
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: software
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:185][             initSDL()] Renderer: direct3d11
```

Full startup logs
```
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:120][             initSDL()] Initializing SDL
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:129][             initSDL()] Initializing SDL_ttf
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:136][             initSDL()] Initializing gamepads
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:563][        initGamepads()] Found 0 joysticks
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:139][             initSDL()] Initializing SDL_mixer
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: direct3d11
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: direct3d12
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: direct3d
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: opengl
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: opengles2
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: vulkan
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: gpu
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:160][             initSDL()] Available render driver: software
[12:53:05][DEBUG][/home/vagrant/breakhack/src/main.c:185][             initSDL()] Renderer: direct3d11
[12:53:05][DEBUG][/home/vagrant/breakhack/src/skillbar.c:35 ][skillbar_set_controller_mode()] Setting controller mode to 0
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:27 ][             db_open()] Opening DB: .data.db
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:69 ][    db_execute_stmnt()] Executing sql: CREATE TABLE IF NOT EXISTS settings_int(key TEXT PRIMARY KEY, value INTEGER)
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:69 ][    db_execute_stmnt()] Executing sql: SELECT * FROM settings_int
[12:53:06][DEBUG][/home/vagrant/breakhack/src/settings.c:82 ][    load_settings_cb()] Loading setting: sound_enabled = 1
[12:53:06][DEBUG][/home/vagrant/breakhack/src/settings.c:82 ][    load_settings_cb()] Loading setting: music_enabled = 1
[12:53:06][DEBUG][/home/vagrant/breakhack/src/settings.c:82 ][    load_settings_cb()] Loading setting: tooltips_enabled = 1
[12:53:06][DEBUG][/home/vagrant/breakhack/src/settings.c:82 ][    load_settings_cb()] Loading setting: how_to_play_shown = 1
[12:53:06][DEBUG][/home/vagrant/breakhack/src/settings.c:82 ][    load_settings_cb()] Loading setting: fullscreen_enabled = 0
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:27 ][             db_open()] Opening DB: .data.db
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:69 ][    db_execute_stmnt()] Executing sql: CREATE TABLE IF NOT EXISTS saves(major_version INTEGER, minor_version INTEGER, patch_version INTEGER, arch INTEGER, save BLOB)
[12:53:06][DEBUG][/home/vagrant/breakhack/src/save.c:62 ][           save_load()] Loading save
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:27 ][             db_open()] Opening DB: .data.db
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:69 ][    db_execute_stmnt()] Executing sql: CREATE TABLE IF NOT EXISTS hiscore(id INTEGER PRIMARY KEY AUTOINCREMENT, time DATETIME DEFAULT CURRENT_TIMESTAMP, gold FLOAT, playerLevel INTEGER, dungeonLevel INTEGER)
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:69 ][    db_execute_stmnt()] Executing sql: CREATE TABLE IF NOT EXISTS hiscore_artifacts(id INTEGER PRIMARY KEY AUTOINCREMENT, hiscoreId INTEGER, artifactId INTEGER, FOREIGN KEY(hiscoreId) REFERENCES hiscore(id))
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:616][        generate_map()] Running lua map script: menumapgen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/io_util.c:28 ][ io_load_file_buffer()] PHYSFS: Loading file menumapgen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:525][       l_load_script()] Loading module: maproombuilder from maproombuilder.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/io_util.c:28 ][ io_load_file_buffer()] PHYSFS: Loading file maproombuilder.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:525][       l_load_script()] Loading module: layoutparser from layoutparser.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/io_util.c:28 ][ io_load_file_buffer()] PHYSFS: Loading file layoutparser.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:525][       l_load_script()] Loading module: monstergen from monstergen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/io_util.c:28 ][ io_load_file_buffer()] PHYSFS: Loading file monstergen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:525][       l_load_script()] Loading module: trapgen from trapgen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/io_util.c:28 ][ io_load_file_buffer()] PHYSFS: Loading file trapgen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:525][       l_load_script()] Loading module: chestgen from chestgen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/io_util.c:28 ][ io_load_file_buffer()] PHYSFS: Loading file chestgen.lua
[12:53:06][DEBUG][/home/vagrant/breakhack/src/random.c:35 ][generate_random_seeds()] Core random seed: 1740765186
[12:53:06][DEBUG][/home/vagrant/breakhack/src/random.c:43 ][generate_random_seeds()] Runtime random seed: 1740765186
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:67 ][        l_print_info()] Map room random seed: 1701748927.0
[12:53:06][DEBUG][/home/vagrant/breakhack/src/map_lua.c:726][        generate_map()] Running lua script menumapgen.lua: Done
[12:53:06][DEBUG][/home/vagrant/breakhack/src/db.c:69 ][    db_execute_stmnt()] Executing sql: SELECT datetime(time, 'localtime') as time, gold, playerLevel, dungeonLevel FROM hiscore ORDER BY gold DESC LIMIT [12:53:48][DEBUG][/home/vagrant/breakhack/src/main.c:835][       handle_events()] Device type changed: 0
[12:53:48][DEBUG][/home/vagrant/breakhack/src/skillbar.c:35 ][skillbar_set_controller_mode()] Setting controller mode to 0
```

Source of logs

![Image](https://github.com/user-attachments/assets/9b547d72-6e7e-4edd-ac83-74b03d41d767)

**Comment by LiquidityC** [comment]
Btw. Did it work to run in fullscreen?

**Comment by BodenMcHale** [comment]
No, `4.1.1` does not allow me to change the window size or type.

But `4.0.3`, Steam version, automatically switched to exclusive fullscreen when I started the game. 

Example of `4.1.1` window, note that the resize button is also disabled. 
![Image](https://github.com/user-attachments/assets/7c57c050-e407-4182-8fa7-daf36415ce67)

**Comment by LiquidityC** [comment]
Ah. Just hit `ctrl-f`

**Comment by BodenMcHale** [comment]
Lmao, yes `ctrl-f` works in `4.1.1` to fullscreen the program.

Interestingly it changes the visual bug from a flicker to a constant.
![Image](https://github.com/user-attachments/assets/83d91049-bd99-4f7c-bd04-2e099f612cd0)

**Comment by BodenMcHale** [comment]
I just installed `version 572.60` for my graphics drivers, and it's almost completely fixed the visual errors on `breakhack 4.1.1` while fullscreen.

It's still quite buggy on the main menu and while not fullscreen.

![Image](https://github.com/user-attachments/assets/61e4aa79-0854-4642-a4b9-bcc3dca5dbb7)
![Image](https://github.com/user-attachments/assets/631ca973-9adb-46b1-b87c-092ce2b01b95)

**Comment by LiquidityC** [comment]
@BodenMcHale Thanks for all your assistance on this one. The flickering rendering was appearing on my new laptop but not my old one. I chalked it down to bad driver support on quite new hardware in linux. But when I saw you got the same behavior I figured something more was up.

**Comment by LiquidityC** [comment]
@BodenMcHale I pushed a new beta build to steam. If you opt into beta you should be getting v4.1.2 which should come without the flickering and hopefully not crash.

**Comment by BodenMcHale** [comment]
Beta 4.1.2 sadly still crashes, but it doesn't flicker!

It does stay open longer than before as well. 

It plays 2 animation cycles of the creatures in the background and I can briefly interact with the main menu buttons.

Proof of beta 4.1.2:
![Image](https://github.com/user-attachments/assets/6f679fa9-5f4f-41d3-a28e-1315fc096e97)

![Image](https://github.com/user-attachments/assets/ae052954-d9ee-4d96-8065-749affc12141)

Example of main menu on open, this will stay for 2-3 seconds before crash.
![Image](https://github.com/user-attachments/assets/7f5c4443-281d-4459-aeec-c69f1f8ff019)

**Comment by LiquidityC** [comment]
Crap. I'm thinking I messed something up with the steam api. I was forced
to make some changes to that in this release. I'll see if I can recreate
that at home. Thanks for the assist

Den tors 6 mars 2025 kl 00:00 skrev Boden McHale ***@***.***>:

**Comment by BodenMcHale** [comment]
If you'd like to send another debug build I’m willing to playtest and provided any needed information.

I deeply wanna play this game lmao

**Comment by LiquidityC** [comment]
> If you'd like to send another debug build I’m willing to playtest and provided any needed information.
> 
> I deeply wanna play this game lmao

You can test the latest beta on steam. There was an upstream patch for SDL which mentioned latest Nvidia drivers. Which I think you have. Hoping that will address the issue. So far I've had no luck reproducing it.

**Comment by LiquidityC** [comment]
@BodenMcHale Forgot to tag you in my last comment. Are you still seeing issues with the beta branch on Steam?

**Comment by BodenMcHale** [comment]
@LiquidityC Sadly yes, it still crashes after a few seconds on Beta branch on Steam.

But interestingly, my Discord overlay activates on it now, which didn't happen before.

Game Version: 4.2.1
![Image](https://github.com/user-attachments/assets/04a2b020-5e67-4d21-9408-041ab3e2fb2d)

**Comment by LiquidityC** [comment]
The flickering issue has been fixed and was unrelated. The crash you are seeing is vexing though. 

I'll prepare some custom builds and upload here for you to test.

**Comment by BodenMcHale** [comment]
Any chance to take another gander at this issue? Would love to see those custom builds if you set em up back in April.

**Comment by LiquidityC** [comment]
@BodenMcHale Ok. So I fixed it. Sort of.

I'm still compiling from linux to windows and it turned out that it's an issue when building a 32-bit executable from a 64-bit linux. I didn't figure it out more then that. The game will be 64-bit only for future releases.

Best I can do with my resources. Sorry it took so long and I hope the 64-bit requirement isn't an issue for you. The beta branch should hold the upcoming release. I'll give it a day or two before I move it to the main.

If you have some time please test it out, confirm that it works. If you have any feedback on the new features then don't be shy.

**Comment by BodenMcHale** [comment]
It's so damn beautiful. 

The animations are sleek and initially shocked me, I couldn't tell if my eyes were playing tricks on me. The fights feel more fluid and dynamic as items fall and I clamber to grab them before enemies attack.

And oh man that map is useful! Finally able to read it properly and have a larger-scale for when I'm more laid back at my setup.

Thank you, and fantastic update!

**Comment by LiquidityC** [comment]
Glad you like it.
